### ISSUE TITLE
Hystrix Fallback Methods listed as Code Smells

### ISSUE THREAD

**Issue by aldorotheo** [1809-Spark-usf/rms-reservation-service#28]
@mgoshorn 

Fallback methods that are necessary for@HystrixCommand are being labeled as two code smells each by Sonarcloud. Specifically, this is because the parameter is listed as never used and that the method is never used. This is because the fallback method needs to share the same signature as the original method, and the method is only executed when an exception occurs when attempting to run the original method. The fallback method is run automatically by Spring so there's no explicit call for the method, and while we could use the parameter for something, there's currently nothing we'd be using it for in the fallback.

**Comment by mgoshorn** [comment]
@aldorotheo Could you provide a link to the Sonarcloud review or PR where it picks up this issue? Not able to find it just scanning branch reviews - there are a lot of them.

**Comment by mgoshorn** [comment]
The only effective way to prevent this exception would have been to provide a regular expression matching the beginning and ending code block. Given the that method describes, this would probably be more work to write than it is worth - As such I've just marked these issues as False Positives through the Sonarcloud UI.
